---
- name: Checking for required variables
  fail: msg="Bailing out. A scout_key is required." 
  when: scout_key is not defined 

- name: Add the scout user
  user: name={{ scout_user }} home=/home/{{ scout_user }} shell=/bin/bash

- name: Create the directory for the public key
  file: path=/home/{{ scout_user }}/.scout
          state=directory

- name: Copy scout_rsa.pub to the /home/{{ scout_user }}/.scout directory
  copy: src=scout_rsa.pub dest=/home/{{ scout_user }}/.scout

- name: Set the proper permissions for .scout
  action: file path=/home/{{ scout_user }}/.scout/ mode=0700 owner={{ scout_user }} group={{ scout_user }}

- name: Set the proper permissions for .scout
  action: file path=/home/{{ scout_user }}/.scout/scout_rsa.pub mode=0400 owner={{ scout_user }} group={{ scout_user }}

- name: Install prerequisite packages
  action: apt pkg={{item}} state=installed
  with_items:
    - sysstat
    - sudo
    - ruby
    - rubygems
  when: ansible_os_family == 'Debian'
  
- name: Install prerequisite packages
  action: yum pkg={{item}} state=installed
  with_items:
    - sysstat
    - sudo
    - ruby
    - rubygems
  when: ansible_os_family == 'RedHat'

- name: Install the scout gem
  gem: name=scout state=present user_install=no

- name: Make sure the cron service is running
  action: service name=cron state=started
  when: ansible_os_family == 'Debian'

- name: Make sure the cron service is running
  action: service name=crond state=started
  when: ansible_os_family == 'Redhat'

- name: Copy the cron job for scout
  action: template src=scout_debian.j2 dest=/etc/cron.d/scout
  when: ansible_os_family == 'Debian'

- name: Copy the cron job for scout
  action: template src=scout_redhat.j2 dest=/etc/cron.d/scout
  when: ansible_os_family == 'RedHat'
